steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --cache=true
    - --destination=eu.gcr.io/$PROJECT_ID/kaniko-demo:$COMMIT_SHA